### ISSUE TITLE
Deployment Issue: Error while deploying latest release (OpenNESS - 20.09)

### ISSUE THREAD

**Issue by pushpraj527** [open-ness/converged-edge-experience-kits#66] opened 2020-10-19 06:54 UTC
Hi,
We tried to deploy the latest release, we are seeing issue with 'pip'.
Also attached the complete deployment log below (2020-10-19_06-13-23_ansible.log).
Please let me know if any other details required for debugging.

2020-10-19 06:24:52,527 p=19271 u=root n=ansible | TASK [docker : install dependencies] **********************************************************************************************************
2020-10-19 06:24:52,528 p=19271 u=root n=ansible | task path: /home/centos/praj/openness-experience-kits/roles/docker/tasks/main.yml:36
2020-10-19 06:25:51,037 p=19271 u=root n=ansible | fatal: [controller]: FAILED! => {
    "changed": false, 
    "cmd": [
        "/usr/bin/pip2", 
        "install", 
        "-r", 
        "/tmp/requirements.txt"
    ]
}

MSG:

stdout: Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname==3.5.0.1 in /usr/lib/python2.7/site-packages (from -r /tmp/requirements.txt (line 4))
Collecting bcrypt==3.1.7 (from -r /tmp/requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/ad/36/9a0227d048e98409f012570f7bef8a8c2373b9c9c5dfbf82963cbae05ede/bcrypt-3.1.7-cp27-cp27mu-manylinux1_x86_64.whl (59kB)
Collecting cached-property==1.5.1 (from -r /tmp/requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/3b/86/85c1be2e8db9e13ef9a350aecd6dea292bd612fa288c2f40d035bb750ded/cached_property-1.5.1-py2.py3-none-any.whl
Collecting certifi==2020.6.20 (from -r /tmp/requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl (156kB)
Collecting cffi==1.14.2 (from -r /tmp/requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/5f/a1/489c4a6fddd981b3b0cd74ce23517f12547bc6e14a5b5cab0cf1db3eb1e6/cffi-1.14.2-cp27-cp27mu-manylinux1_x86_64.whl (388kB)
Collecting chardet==3.0.4 (from -r /tmp/requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Requirement already satisfied (use --upgrade to upgrade): configobj==4.7.2 in /usr/lib/python2.7/site-packages (from -r /tmp/requirements.txt (line 10))
Collecting cryptography==3.0 (from -r /tmp/requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/66/58/d7ff652d30e8cbabd8946b3116fba73b39a73ea9c63943b3c1bf3cfcf190/cryptography-3.0-cp27-cp27mu-manylinux1_x86_64.whl (2.7MB)
Requirement already satisfied (use --upgrade to upgrade): decorator==3.4.0 in /usr/lib/python2.7/site-packages (from -r /tmp/requirements.txt (line 12))
Collecting docker==3.7.3 (from -r /tmp/requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/09/da/7cc7ecdcd01145e9924a8ccbe9c1baf3a362fc75d4cb150676eb5231ea60/docker-3.7.3-py2.py3-none-any.whl (134kB)
Collecting docker-compose==1.24.1 (from -r /tmp/requirements.txt (line 14))
  Downloading https://files.pythonhosted.org/packages/dd/e6/1521d1dfd9c0da1d1863b18e592d91c3df222e55f258b9876fa1e59bc4b5/docker_compose-1.24.1-py2.py3-none-any.whl (134kB)
Collecting docker-pycreds==0.4.0 (from -r /tmp/requirements.txt (line 15))
  Downloading https://files.pythonhosted.org/packages/f5/e8/f6bd1eee09314e7e6dee49cbe2c5e22314ccdb38db16c9fc72d2fa80d054/docker_pycreds-0.4.0-py2.py3-none-any.whl
Collecting dockerpty==0.4.1 (from -r /tmp/requirements.txt (line 16))
  Downloading https://files.pythonhosted.org/packages/8d/ee/e9ecce4c32204a6738e0a5d5883d3413794d7498fe8b06f44becc028d3ba/dockerpty-0.4.1.tar.gz
Collecting docopt==0.6.2 (from -r /tmp/requirements.txt (line 17))
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting enum34==1.1.10 (from -r /tmp/requirements.txt (line 18))
  Downloading https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
Collecting functools32==3.2.3.post2 (from -r /tmp/requirements.txt (line 19))
  Downloading https://files.pythonhosted.org/packages/c5/60/6ac26ad05857c601308d8fb9e87fa36d0ebf889423f47c3502ef034365db/functools32-3.2.3-2.tar.gz
Collecting idna==2.7 (from -r /tmp/requirements.txt (line 20))
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
Requirement already satisfied (use --upgrade to upgrade): iniparse==0.4 in /usr/lib/python2.7/site-packages (from -r /tmp/requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): ipaddress==1.0.16 in /usr/lib/python2.7/site-packages (from -r /tmp/requirements.txt (line 22))
Collecting jsonschema==2.6.0 (from -r /tmp/requirements.txt (line 23))
  Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting paramiko==2.7.1 (from -r /tmp/requirements.txt (line 24))
  Downloading https://files.pythonhosted.org/packages/06/1e/1e08baaaf6c3d3df1459fd85f0e7d2d6aa916f33958f151ee1ecc9800971/paramiko-2.7.1-py2.py3-none-any.whl (206kB)
Requirement already satisfied (use --upgrade to upgrade): perf==0.1 in /usr/lib64/python2.7/site-packages (from -r /tmp/requirements.txt (line 25))
Collecting pycparser==2.20 (from -r /tmp/requirements.txt (line 26))
  Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
Requirement already satisfied (use --upgrade to upgrade): pycurl==7.19.0 in /usr/lib64/python2.7/site-packages (from -r /tmp/requirements.txt (line 27))
Requirement already satisfied (use --upgrade to upgrade): pygobject==3.22.0 in /usr/lib64/python2.7/site-packages (from -r /tmp/requirements.txt (line 28))
Requirement already satisfied (use --upgrade to upgrade): pygpgme==0.3 in /usr/lib64/python2.7/site-packages (from -r /tmp/requirements.txt (line 29))
Requirement already satisfied (use --upgrade to upgrade): pyliblzma==0.5.3 in /usr/lib64/python2.7/site-packages (from -r /tmp/requirements.txt (line 30))
Collecting PyNaCl==1.4.0 (from -r /tmp/requirements.txt (line 31))
  Downloading https://files.pythonhosted.org/packages/de/63/bb36279da38df643c6df3a8a389f29a6ff4a8854468f4c9b9d925b27d57d/PyNaCl-1.4.0-cp27-cp27mu-manylinux1_x86_64.whl (964kB)
Requirement already satisfied (use --upgrade to upgrade): python-linux-procfs==0.4.9 in /usr/lib/python2.7/site-packages (from -r /tmp/requirements.txt (line 32))
Requirement already satisfied (use --upgrade to upgrade): pyudev==0.15 in /usr/lib/python2.7/site-packages (from -r /tmp/requirements.txt (line 33))
Requirement already satisfied (use --upgrade to upgrade): pyxattr==0.5.1 in /usr/lib64/python2.7/site-packages (from -r /tmp/requirements.txt (line 34))
Collecting PyYAML==5.1 (from -r /tmp/requirements.txt (line 35))
  Downloading https://files.pythonhosted.org/packages/9f/2c/9417b5c774792634834e730932745bc09a7d36754ca00acf1ccd1ac2594d/PyYAML-5.1.tar.gz (274kB)
Collecting requests==2.20.1 (from -r /tmp/requirements.txt (line 36))
  Downloading https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl (57kB)
Requirement already satisfied (use --upgrade to upgrade): schedutils==0.4 in /usr/lib64/python2.7/site-packages (from -r /tmp/requirements.txt (line 37))
Collecting six==1.15.0 (from -r /tmp/requirements.txt (line 38))
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting slip==0.4.0 (from -r /tmp/requirements.txt (line 39))

:stderr:   Could not find a version that satisfies the requirement slip==0.4.0 (from -r /tmp/requirements.txt (line 39)) (from versions: 0.1, 0.2, 0.3.8, 20191113)
No matching distribution found for slip==0.4.0 (from -r /tmp/requirements.txt (line 39))
You are using pip version 8.1.2, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

2020-10-19 06:25:51,038 p=19271 u=root n=ansible | NO MORE HOSTS LEFT ****************************************************************************************************************************
2020-10-19 06:25:51,054 p=19271 u=root n=ansible | PLAY RECAP ************************************************************************************************************************************
2020-10-19 06:25:51,055 p=19271 u=root n=ansible | controller                 : ok=70   changed=22   unreachable=0    failed=1    skipped=71   rescued=0    ignored=0   

[2020-10-19_06-13-23_ansible.log](https://github.com/open-ness/openness-experience-kits/files/5399615/2020-10-19_06-13-23_ansible.log)

**Comment by jakubrym** [comment] 2020-10-26 09:20
Hi @pushpraj527,
This issue isn't caused by "pip" it's caused by "No matching distribution found for slip==0.4.0".
Is this issue still appearing?

**Comment by pushpraj527** [comment] 2020-10-26 11:08
Hello @jakubrym 
Yes, This issue is still appearing.

**Comment by jakubrym** [comment] 2020-10-26 13:19
@pushpraj527 Please try changing slip==0.4.0 to python-slip==0.4.0 and slip.dbus==0.4.0 to python-slip-dbus==0.4.0 in openness-experience-kits/roles/docker/files/requirements.txt . Let me know if it helps.

**Comment by pushpraj527** [comment] 2020-10-26 13:42
Hi @jakubrym. 

We tried the suggested changes, but we are still getting the issue mentioned below.

Collecting python-slip==0.4.0 (from -r /tmp/requirements.txt (line 39))

:stderr: Could not find a version that satisfies the requirement python-slip==0.4.0 (from -r /tmp/requirements.txt (line 39)) (from versions: )
No matching distribution found for python-slip==0.4.0 (from -r /tmp/requirements.txt (line 39))
You are using pip version 8.1.2, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by jakubrym** [comment] 2020-11-03 12:03
Hi @pushpraj527,

Yesterday I deployed OpenNESS both controller and node, and didn't encounter this issue. Please try deploying OpenNESS on clean setup.

**Comment by jakubrym** [comment] 2020-11-06 12:47
Closing ticket. Will reopen when issue repeats.

**Closed as completed by jakubrym** 2020-11-06 12:47 UTC
