### ISSUE TITLE
Error when deploying edge node

### ISSUE THREAD

**Issue by jingzhu77** [open-ness/converged-edge-experience-kits#36] opened 2020-07-16 15:32 UTC
Got the following when running the playbook (./deploye_ne.sh single): 

go: modernc.org/strutil@v1.0.0: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/f48599000415ab70c2f95dc7528c585820ed37ee15d27040a550487e83a41748: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly

It seems to be related to a bug in Gitlab based on this link: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/63512

**Comment by tomaszwesolowski** [comment] 2020-07-17 06:40
Hi, 
Did this error occurred just once or multiple times? Can you provide more console log output?
Thanks

**Comment by pavanats** [comment] 2020-07-22 07:15
Have u tried these steps:
yum remove git* -y
yum install -y --enablerepo=ius-archive git2u-all

**Comment by bmknaidu555** [comment] 2020-07-27 20:10
Hi,

I am also facing the same issue as mentioned by @jingzhu77. 

1. Downloaded the openness-experience-kits/ and ran "deploy_ne.sh controller"
2. During the installation, I got an error while executing the task  **TASK [telemetry/tas : build TAS]** .

**_Below are the console logs of the issue:_**

TASK [telemetry/tas : build TAS] *********************************************************************************************************************
task path: /home/sysadmin/Murali/openness/openness-experience-kits/roles/telemetry/tas/tasks/main.yml:154
fatal: [controller]: FAILED! => {
    "changed": true, 
    "cmd": "source /etc/profile && make build", 
    "delta": "0:00:04.794462", 
    "end": "2020-07-28 01:26:11.583368", 
    "rc": 2, 
    "start": "2020-07-28 01:26:06.788906"
}

STDOUT:

CGO_ENABLED=0 GO111MODULE=on go build -ldflags="-s -w" -o ./bin/controller ./cmd/tas-policy-controller


STDERR:

go: finding modernc.org/xc v1.0.0
go: finding modernc.org/golex v1.0.0
go: finding modernc.org/mathutil v1.0.0
go: finding modernc.org/cc v1.0.0
go: finding modernc.org/strutil v1.0.0
go: modernc.org/cc@v1.0.0: git fetch -f https://gitlab.com/cznic/cc refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/3dac616a9d80602010c4792ef9c0e9d9812a1be8e70453e437e9792978075db6: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: modernc.org/strutil@v1.0.0: git fetch -f https://gitlab.com/cznic/strutil refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/f48599000415ab70c2f95dc7528c585820ed37ee15d27040a550487e83a41748: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: modernc.org/golex@v1.0.0: git fetch -f https://gitlab.com/cznic/golex refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/9aae2d4c6ee72eb1c6b65f7a51a0482327c927783dea53d4058803094c9d8039: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: modernc.org/mathutil@v1.0.0: git fetch -f https://gitlab.com/cznic/mathutil refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/fb72eb2422fda47ac75ca695d44b06b82f3df3c5308e271486fca5e320879130: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: modernc.org/xc@v1.0.0: git fetch -f https://gitlab.com/cznic/xc refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/29fc2f846f24ce3630fdd4abfc664927c4ad22f98a3589050facafa0991faada: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: error loading module requirements
make: *** [build] Error 1


MSG:

non-zero return code

**Comment by pavanats** [comment] 2020-07-28 02:43
We were facing the same issue and that got resolved by executing the commands(To install a newer version of git), which were earlier suggested by Mokhtar.

yum remove git* -y
yum install -y --enablerepo=ius-archive git2u-all

________________________________

**Comment by tomaszwesolowski** [comment] 2020-07-28 07:03
hi @bmknaidu555, 
Can you verify if @pavanats solution works?

**Comment by bmknaidu555** [comment] 2020-07-28 07:06
> hi @bmknaidu555,
> Can you verify if @pavanats solution works?

Hi @tomaszwesolowski 

@pavanats solution worked for me. Thanks for the help.

**Comment by i-kwilk** [comment] 2020-09-01 08:56
Closing as the issue is solved.

**Closed as completed by i-kwilk** 2020-09-01 08:56 UTC
Labels: help wanted, OpenNESS-2006
