### ISSUE TITLE
Error msg in deploying controller with Ansible script

### ISSUE THREAD

**Issue by pavanats** [open-ness/converged-edge-experience-kits#31] opened 2020-07-07 17:04 UTC
I have come across this error a couple of times. Tried different things looking at various use forums, not sure why this occuring.

go: modernc.org/strutil@v1.0.0: git fetch -f https://gitlab.com/cznic/strutil refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/f48599000415ab70c2f95dc7528c585820ed37ee15d27040a550487e83a41748: exit status 128:
        error: RPC failed; result=22, HTTP code = 404
        fatal: The remote end hung up unexpectedly

I have a VM which has openness experience kit installed and on the same VM I am installing OpenNESS controller.

**Comment by amr-mokhtar** [comment] 2020-07-07 19:37
It is not a good idea to install OEK and the controller on the same node. Typically, they should be separated.
RE the error, what was causing it?

**Comment by mehashu** [comment] 2020-07-08 04:07
@pavanats, We were facing the same issue and that got resolved by executing the commands(To install a newer version of git), which were earlier suggested by Mokhtar.

yum remove git* -y
yum install -y --enablerepo=ius-archive git2u-all

**Comment by amr-mokhtar** [comment] 2020-07-08 15:34
Duplicate of #27

**Closed as completed by amr-mokhtar** 2020-07-08 15:34 UTC
Labels: help wanted, OpenNESS-2006
