### ISSUE TITLE
CrashLoopBackOff error for openvino-cons-app  pod

### ISSUE THREAD

**Issue by pavanats** [open-ness/converged-edge-experience-kits#40] opened 2020-07-24 15:31 UTC
Hi,
I am trying to run the openvino application. I could run the producer pod but the consumer pod fails.  Output of kubectl describe command is shown below. While, I am debugging this issue, please let us know if this is a known issue.

### [root@controller consumer]# kubectl describe pods openvino-cons-app
Name:         openvino-cons-app
Namespace:    default
Priority:     0
Node:         node01/146.0.237.30
Start Time:   Thu, 23 Jul 2020 18:46:51 +0200
Labels:       name=openvino-cons-app
Annotations:  ovn.kubernetes.io/allocated: true
              ovn.kubernetes.io/cidr: 10.16.0.0/16
              ovn.kubernetes.io/gateway: 10.16.0.1
              ovn.kubernetes.io/ip_address: 10.16.0.9
              ovn.kubernetes.io/logical_switch: ovn-default
              ovn.kubernetes.io/mac_address: 0e:4f:1d:10:00:0a
Status:       Running
IP:           10.16.0.9
IPs:
  IP:  10.16.0.9
Containers:
  openvino-cons-app:
    Container ID:   docker://f2b1d86372c70dbb939453176cc84051a9ca005e6ad3d1cc114245219026ff84
    Image:          openvino-cons-app:1.0
    Image ID:       docker://sha256:6cf9eefe7638b01a1700d99c3cd0cfe90539cf359dd09f6f8dfe7ad00aafa11a
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 24 Jul 2020 17:28:10 +0200
      Finished:     Fri, 24 Jul 2020 17:28:11 +0200
    Ready:          False
    Restart Count:  266
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xqj7r (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-xqj7r:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-xqj7r
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                     From             Message
  ----     ------   ----                    ----             -------
  Normal   Created  27m (x262 over 22h)     kubelet, node01  Created container openvino-cons-app
  Normal   Pulled   22m (x263 over 22h)     kubelet, node01  Container image "openvino-cons-app:1.0" already present on machine
  Warning  BackOff  2m31s (x6259 over 22h)  kubelet, node01  Back-off restarting failed container

**Comment by amr-mokhtar** [comment] 2020-07-27 10:26
Hi @pavanats, were you successful running the OpenVINO sample app before? If yes, what is different with your setup this time? What are the logs from the app?
```shell
kubectl logs openvino-cons-app
```

**Comment by pavanats** [comment] 2020-07-27 11:06
Hi,
I havent run openvino earlier. The output of kubectl logs is below:

[setupvars.sh] OpenVINO environment initialized
# command-line-arguments
./openvino.go:64:9: undefined: err
./openvino.go:65:16: undefined: err
./openvino.go:70:9: undefined: err
./openvino.go:71:16: undefined: err
./start.sh: line 10: fg: no job control

Pavan
________________________________

**Comment by amr-mokhtar** [comment] 2020-07-27 11:55
OK. The above issue is duplicate of https://github.com/open-ness/edgeapps/issues/20
It should have been fixed by this PR: https://github.com/open-ness/edgeapps/pull/23

**Closed as completed by amr-mokhtar** 2020-07-27 11:55 UTC
Labels: help wanted, OpenNESS-2006
